### ISSUE TITLE
Forking is disabled

### ISSUE THREAD

**Issue by VandyTheCoder** [soramitsukhmer/handbook#1]
**Describe**
The purpose of the task is to request to enable handbook repo able to fork, so we can allow other member to submit the fix or enhancement.

**Reviewers**
@socheatsok78

**Comment by socheatsok78** [comment]
I've made the repo public, you should be able to make a "folk" now!

**Comment by VandyTheCoder** [comment]
@socheatsok78  Thank u, bong
